#!/bin/sh
# Generate a container-local ~/.gitconfig that inherits host settings but
# overrides credential helpers to use the container's gh CLI.
#
# The host's .gitconfig is bind-mounted read-only at ~/.gitconfig-host; the
# first include pulls in user.name/user.email/aliases from it. No SSH keys or
# host credential stores are mounted — GitHub auth flows through `gh auth
# git-credential` (GH_TOKEN passthrough or `gh auth login` in the container).
#
# This file is regenerated on every container create, so anything written to
# it with plain `git config --global` dies on rebuild. Persistent
# container-local settings (e.g. identity when the host has none) belong in
# ~/.config/git/config — volume-backed, and included last so it wins.

GITCONFIG="$HOME/.gitconfig"
GH_BIN="$(command -v gh 2>/dev/null || echo /usr/bin/gh)"

mkdir -p "$HOME/.config/git"

cat > "$GITCONFIG" <<EOF
# Auto-generated by .devcontainer/setup-gitconfig.sh — do not edit; this file
# is regenerated on every container create. Persistent container-local
# settings belong in ~/.config/git/config (volume-backed, included last).

# Host settings (user.name, user.email, aliases, ...) are inherited here.
[include]
    path = ~/.gitconfig-host

# Container defaults — placed after the host include so they win over
# host-only settings that misbehave in Linux checkouts (e.g.
# core.autocrlf=true smudging CRLF into files).
[init]
    defaultBranch = main
[core]
    autocrlf = input

# Credential helpers for the container environment. The empty entries reset
# helpers inherited from the host config — the unscoped one and the
# GitHub-scoped ones (Windows credential manager, osxkeychain, ...) — which
# reference binaries that do not exist inside the container.
[credential]
    helper =

[credential "https://github.com"]
    helper =
    helper = !${GH_BIN} auth git-credential

[credential "https://gist.github.com"]
    helper =
    helper = !${GH_BIN} auth git-credential

# Persistent container-local overrides — kept in the ~/.config volume so they
# survive rebuilds; included last so they take precedence over everything.
[include]
    path = ~/.config/git/config
EOF

echo "setup-gitconfig: wrote $GITCONFIG (gh: $GH_BIN)"
